site_name: Doug Redden CV
site_url: https://DougRzz.github.io/CV/
site_author: Doug Redden

# Repository
repo_name: DougRzz/CV
repo_url: https://github.com/DougRzz/CV

# Customization
extra_css: [templates_overrides/extra.css]

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details
  - md_in_html
  - attr_list
  
# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  # - markdown-exec:
  #       exec: true
  # - gen-files:
  #     scripts:
  #       - docs/gen_pages.py       


theme:
    name: material
    custom_dir: docs/templates_overrides    
    palette:
      - scheme: default
        primary: stylesheets/extra.css
        accent: indigo
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        primary: blue grey
        accent: indigo
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

    font:
      text: Roboto
      code: Roboto Mono
    favicon: assets/favicon.png
    icon:
      logo: material/chess-king

    features:
      # - announce.dismiss
      - content.action.edit
      - content.action.view
      - content.code.annotate
      - content.code.copy
      # - content.code.select
      - content.tabs.link
      - content.tooltips
      # - header.autohide
      # - navigation.expand
      - navigation.footer
      # - navigation.indexes
      - navigation.instant
      - navigation.path
      # - navigation.prune
      - navigation.sections
      - navigation.tabs
      # - navigation.tabs.sticky
      - navigation.top
      - navigation.tracking
      - search.highlight
      - search.share
      - search.suggest
      - toc.follow
      - toc.integrate




# Customization
extra:
  annotate:
    json: [.s2]
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/DougRzz
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/doug-redden/
nav:
    - Doug Redden: index.md

